
package fr.techlab.businessv2services.ws.savetask;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5.redhat-630310
 * 2018-05-02T23:30:14.064+02:00
 * Generated source version: 3.1.5.redhat-630310
 */

@WebFault(name = "functionnalException", targetNamespace = "http://www.techlab.fr/SGOV2/Schemas/FunctionnalException")
public class FunctionnalException extends Exception {
    
    private fr.techlab.sgov2.schemas.functionnalexception.FunctionnalException functionnalException;

    public FunctionnalException() {
        super();
    }
    
    public FunctionnalException(String message) {
        super(message);
    }
    
    public FunctionnalException(String message, Throwable cause) {
        super(message, cause);
    }

    public FunctionnalException(String message, fr.techlab.sgov2.schemas.functionnalexception.FunctionnalException functionnalException) {
        super(message);
        this.functionnalException = functionnalException;
    }

    public FunctionnalException(String message, fr.techlab.sgov2.schemas.functionnalexception.FunctionnalException functionnalException, Throwable cause) {
        super(message, cause);
        this.functionnalException = functionnalException;
    }

    public fr.techlab.sgov2.schemas.functionnalexception.FunctionnalException getFaultInfo() {
        return this.functionnalException;
    }
}
