package fr.techlab.businessv2services.ws.savetask;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630310
 * 2018-05-02T23:30:14.082+02:00
 * Generated source version: 3.1.5.redhat-630310
 * 
 */
@WebService(targetNamespace = "http://www.techlab.fr/businessv2services/WS/saveTask", name = "saveTaskPortType")
@XmlSeeAlso({fr.techlab.sgov2.schemas.functionnalexception.ObjectFactory.class, fr.techlab.sgov2.schemas.technicalexception.ObjectFactory.class, fr.techlab.sgov2.schemas.savetask.savetaskresponse.ObjectFactory.class, fr.techlab.sgov2.schemas.context.ObjectFactory.class, fr.techlab.sgov2.schemas.savetask.savetaskrequest.ObjectFactory.class, com.techlab.schemas.businessv2_services.sharedresources.partners.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SaveTaskPortType {

    @WebMethod(action = "/SGOV2/Services/saveTask/saveTask/saveTaskEndpoint/saveTaskOp")
    @WebResult(name = "saveTaskResponse", targetNamespace = "http://www.techlab.fr/SGOV2/Schemas/SaveTask/SaveTaskResponse.xsd", partName = "parameters")
    public fr.techlab.sgov2.schemas.savetask.savetaskresponse.SaveTaskResponse saveTaskOp(
        @WebParam(partName = "parameters", name = "saveTaskRequest", targetNamespace = "http://www.techlab.fr/SGOV2/Schemas/SaveTask/SaveTaskRequest.xsd")
        fr.techlab.sgov2.schemas.savetask.savetaskrequest.SaveTaskRequest parameters
    ) throws FunctionnalException, TechnicalException;
}
